# Generated by Django 3.2.7 on 2021-09-08 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('vaqti', models.TimeField()),
                ('bajarish', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sana', 'vaqti'),
            },
        ),
    ]
