# Generated by Django 3.2.7 on 2021-09-08 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ish',
            options={'ordering': ('sana', 'vaqti'), 'verbose_name_plural': 'Ishlar'},
        ),
        migrations.AlterField(
            model_name='ish',
            name='sana',
            field=models.DateField(default=datetime.date(2021, 9, 8)),
        ),
    ]
