# Generated by Django 3.2.9 on 2021-11-06 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210908_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ish',
            name='sana',
            field=models.DateField(default=datetime.date(2021, 11, 6)),
        ),
    ]
